"""
Create a program that will play the “cows and bulls” game with the user.
The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
For every digit that the user guessed correctly in the correct place, they have a “cow”.
For every digit the user guessed correctly in the wrong place is a “bull.”
Every time the user makes a guess, tell them how many “cows” and “bulls” they have.
Once the user guesses the correct number, the game is over.
Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038.
An example interaction could look like this:

  Welcome to the Cows and Bulls Game!
  Enter a number:
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...

Until the user guesses the number.
"""

import random


def BullsCows(guess, number):
    guess_list = [num for num in str(guess)]
    number_list = [num for num in str(number)]
    bulls = 0
    cows = 0
    for g, n in zip(guess_list, number_list):
        bulls += 1 if g == n else 0

    for g in set(guess_list):
        cows += 1 if g in number_list else 0

    return [bulls, cows-bulls]


secret_number = random.randint(100, 999)
#secret_number = 123
score = False
tries = 1

#print(BullsCows(413, 123))

debug = 1
while score == False and debug == 1:
    number = int(input("Please enter your number: "))
    if number == secret_number:
        print("Congratulations! You have won!")
        print("Number of tries:", tries)
        score = True
    else:
        print("You did not guess the number")
        print("Bulls:", BullsCows(number, secret_number)[0],end=' ')
        print("Cows:", BullsCows(number, secret_number)[1])
        print("Number of tries: {}. Please try again".format(tries))
        '''
        if(number>secret_number):
            print("try lower")
        else:
            print("try higher")
        '''
        tries += 1
    print(30 * "-")

print("Game executed.")
